FROM python:3.8

ENV PYTHONUNBUFFERED 1

ARG ENV=local

ARG APP_TIMEOUT

WORKDIR /backend
COPY . /backend

RUN pip install -r requirements.txt --no-cache-dir && \
    sed -i -e 's/{% load staticfiles %}/{% load static %}/' /usr/local/lib/python3.8/site-packages/rest_framework_swagger/templates/rest_framework_swagger/index.html

COPY ./openapi.py /usr/local/lib/python3.8/site-packages/rest_framework/schemas

ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]
