# Generated by Django 4.0.1 on 2022-03-01 22:45

from django.db import migrations, models
import django.db.models.deletion
import dorapi.models.muser_model
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('series', models.CharField(choices=[('てんコミ', 'tencomi'), ('大長編', 'chohen'), ('FFランド', 'f_land'), ('カラー', 'col_collect'), ('プラス', 'plus'), ('大全集', 'f_collect'), ('映ドラ', 'movie')], max_length=8192)),
                ('volume', models.CharField(max_length=8192)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('sub', models.CharField(default=dorapi.models.muser_model.random_char, max_length=8192, unique=True)),
                ('name', models.CharField(blank=True, max_length=8192)),
                ('email', models.CharField(max_length=8192)),
                ('authority', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('type', models.IntegerField(choices=[(0, 'admin'), (1, 'machine'), (2, 'user')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MGadget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=8192)),
                ('ruby', models.CharField(max_length=8192)),
                ('desc', models.CharField(max_length=8192)),
                ('books', models.ForeignKey(db_column='mbook_id', on_delete=django.db.models.deletion.CASCADE, related_name='mbooks', related_query_name='mbook', to='dorapi.mbook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
