# Generated by Django 4.0.1 on 2022-03-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorapi', '0002_gadgetlink_mgadget_linked_gadgets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgadget',
            name='href',
            field=models.CharField(default='/gadget/', max_length=8192),
            preserve_default=False,
        ),
    ]
